{
  "nodes": [
    {
      "type": "text",
      "x": "899px",
      "y": "1080px",
      "w": "466px",
      "h": "223px",
      "title": "文本框测试",
      "id": "node-8",
      "content": "<span style=\"font-size: 23px;\">我们测试一下中文</span><div><div><span style=\"font-size: 23px;\"><br></span><div><span style=\"font-size: 24px;\"><div style=\"\"><b><font color=\"#3366cc\">蓝色</font> <font color=\"#339933\">绿色</font> <font color=\"#cc3333\">红色</font> <span style=\"font-family: &quot;JetBrains Mono&quot;, monospace;\"><u><strike>下划线</strike></u></span>&nbsp;<i>斜体</i></b></div></span><div></div></div></div></div>",
      "lh": "1.8"
    },
    {
      "type": "text",
      "x": "579px",
      "y": "232px",
      "w": "462px",
      "h": "261px",
      "title": "文本框测试",
      "id": "node-9",
      "content": "<div style=\"text-align: center; \"><span style=\"font-size: 26px;\">居中</span></div><span style=\"font-size: 34px;\"><div><span style=\"background-color: transparent; letter-spacing: 0.2px;\">有大</span><span style=\"background-color: transparent; letter-spacing: 0.2px; font-size: 26px;\">有小<b>有粗体</b><i>有斜体</i></span></div></span><div style=\"text-align: right;\"><span style=\"font-size: 26px;\">右对齐</span></div>",
      "lh": "2.1"
    },
    {
      "type": "image",
      "x": "1171px",
      "y": "527px",
      "w": "438px",
      "h": "459px",
      "title": "图片测试",
      "id": "node-10",
      "src": "https://www.xingye-blog.xyz/img/DeltaChat/02.png"
    },
    {
      "type": "markdown",
      "x": "664px",
      "y": "650px",
      "w": "240px",
      "h": "254px",
      "title": "Markdown测试",
      "id": "node-11",
      "source": "# 测试\n\n**粗体**\n\n普通文本\n\n*斜体*\n\n- 第一个序号\n- 第二个序号"
    }
  ],
  "connections": [
    {
      "from": "node-4",
      "to": "node-1"
    },
    {
      "from": "node-2",
      "to": "node-4"
    },
    {
      "from": "node-3",
      "to": "node-1"
    },
    {
      "from": "node-6",
      "to": "node-8"
    },
    {
      "from": "node-8",
      "to": "node-5"
    },
    {
      "from": "node-7",
      "to": "node-5"
    },
    {
      "from": "node-9",
      "to": "node-11"
    },
    {
      "from": "node-11",
      "to": "node-8"
    },
    {
      "from": "node-10",
      "to": "node-8"
    }
  ]
}