{
  "nodes": [
    {
      "type": "text",
      "x": "482px",
      "y": "630px",
      "w": "466px",
      "h": "223px",
      "title": "文本框演示",
      "id": "node-1",
      "locked": false,
      "minimized": false,
      "fontSize": "",
      "content": "<span style=\"font-size: 23px;\">我们测试一下中文</span><div><div><span style=\"font-size: 23px;\"><br></span><div><span style=\"font-size: 24px;\"><div style=\"\"><b><font color=\"#3366cc\">蓝色</font> <font color=\"#339933\">绿色</font> <font color=\"#cc3333\">红色</font> <span style=\"font-family: &quot;JetBrains Mono&quot;, monospace;\"><u><strike>下划线</strike></u></span>&nbsp;<i>斜体</i></b></div></span><div></div></div></div></div>",
      "lh": "1.8"
    },
    {
      "type": "text",
      "x": "29px",
      "y": "184px",
      "w": "462px",
      "h": "261px",
      "title": "文本框演示",
      "id": "node-2",
      "locked": false,
      "minimized": false,
      "fontSize": "",
      "content": "<div style=\"text-align: center; \"><span style=\"font-size: 26px;\">居中</span></div><span style=\"font-size: 34px;\"><div><span style=\"background-color: transparent; letter-spacing: 0.2px;\">有大</span><span style=\"background-color: transparent; letter-spacing: 0.2px; font-size: 26px;\">有小<b>有粗体</b><i>有斜体</i></span></div></span><div style=\"text-align: right;\"><span style=\"font-size: 26px;\">右对齐</span></div>",
      "lh": "2.1"
    },
    {
      "type": "image",
      "x": "561px",
      "y": "83px",
      "w": "287px",
      "h": "457px",
      "title": "图片演示",
      "id": "node-3",
      "locked": false,
      "minimized": false,
      "fontSize": "",
      "src": "https://www.xingye-blog.xyz/img/DeltaChat/02.png"
    },
    {
      "type": "markdown",
      "x": "85px",
      "y": "559px",
      "w": "302px",
      "h": "268px",
      "title": "Markdown 演示",
      "id": "node-4",
      "locked": false,
      "minimized": false,
      "fontSize": "",
      "source": "# 测试\n\n**粗体**\n\n普通文本\n\n*斜体*\n\n- 第一个序号\n- 第二个序号"
    },
    {
      "type": "math",
      "x": "1318px",
      "y": "353px",
      "w": "285px",
      "h": "170px",
      "title": "公式演示",
      "id": "node-5",
      "locked": false,
      "minimized": false,
      "fontSize": "20",
      "source": "\\sin(x)+\\cos(x)"
    },
    {
      "type": "todo",
      "x": "878px",
      "y": "397px",
      "w": "402px",
      "h": "",
      "title": "TODO 演示",
      "id": "node-6",
      "locked": false,
      "minimized": false,
      "fontSize": "",
      "content": "上传代码到 GitHub 并进行部署",
      "lh": "1.8"
    },
    {
      "type": "group",
      "x": "1080px",
      "y": "572px",
      "w": "",
      "h": "",
      "title": "分组演示",
      "id": "node-7",
      "locked": false,
      "minimized": false,
      "fontSize": "",
      "content": "最小化（右上角的 -）和移动位置（拖动标题栏）会同步更改相连节点<br><br>显示/隐藏按键（左上角的倒三角）修改相连节点的显隐性<div><br></div><div>如果相连节点不想受分组节点的控制，可以锁定或者临时断开连线</div>",
      "lh": "1.8"
    },
    {
      "type": "text",
      "x": "907px",
      "y": "109px",
      "w": "",
      "h": "",
      "title": "说明",
      "id": "node-8",
      "locked": false,
      "minimized": false,
      "fontSize": "",
      "content": "制作这个页面的想法来源于 ommwriter：https://ommwriter.com<div><br></div><div style=\"text-align: center; \">我给这个页面的定位是临时的内容记录</div>",
      "lh": "1.8"
    }
  ],
  "connections": [
    {
      "from": "node-2",
      "to": "node-4",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-3",
      "to": "node-1",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-9",
      "to": "node-11",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-11",
      "to": "node-8",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-10",
      "to": "node-8",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-12",
      "to": "node-10",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-11",
      "to": "node-13",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-11",
      "to": "node-12",
      "fromPort": "right",
      "toPort": "left"
    },
    {
      "from": "node-13",
      "to": "node-10",
      "fromPort": "right",
      "toPort": "left"
    },
    {
      "from": "node-15",
      "to": "node-16",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-14",
      "to": "node-16",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-6",
      "to": "node-7",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-5",
      "to": "node-7",
      "fromPort": "bottom",
      "toPort": "top"
    },
    {
      "from": "node-4",
      "to": "node-1",
      "fromPort": "right",
      "toPort": "left"
    }
  ]
}