{
  "nodes": [
    {
      "type": "text",
      "x": "344px",
      "y": "272px",
      "w": "429px",
      "h": "202px",
      "title": "文本框测试",
      "content": "<span style=\"font-size: 23px;\">我们测试一下中文</span><div><div><span style=\"font-size: 23px;\"><br></span><div><span style=\"font-size: 24px;\"><div style=\"\"><b><font color=\"#3366cc\">蓝色</font> <font color=\"#339933\">绿色</font> <font color=\"#cc3333\">红色</font> <span style=\"font-family: &quot;JetBrains Mono&quot;, monospace;\"><u><strike>下划线</strike></u></span>&nbsp;<i>斜体</i></b></div></span><div></div></div></div></div>",
      "lh": "1.8"
    },
    {
      "type": "text",
      "x": "645px",
      "y": "73px",
      "w": "473px",
      "h": "270px",
      "title": "文本框测试",
      "content": "<div style=\"text-align: center; \"><span style=\"font-size: 26px;\">居中</span></div><span style=\"font-size: 34px;\"><div><span style=\"background-color: transparent; letter-spacing: 0.2px;\">有大</span><span style=\"background-color: transparent; letter-spacing: 0.2px; font-size: 26px;\">有小<b>有粗体</b><i>有斜体</i></span></div></span><div style=\"text-align: right;\"><span style=\"font-size: 26px;\">右对齐</span></div>",
      "lh": "2.1"
    },
    {
      "type": "image",
      "x": "877px",
      "y": "384px",
      "w": "438px",
      "h": "459px",
      "title": "图片测试",
      "src": "https://www.xingye-blog.xyz/img/DeltaChat/02.png"
    },
    {
      "type": "markdown",
      "x": "461px",
      "y": "519px",
      "w": "240px",
      "h": "254px",
      "title": "Markdown测试",
      "source": "# 测试\n\n**粗体**\n\n普通文本\n\n*斜体*\n\n- 第一个序号\n- 第二个序号"
    }
  ]
}